### ISSUE TITLE
Document how to use the NXT HiTechnic Gyroscope sensor on segway.py

### ISSUE THREAD

**Issue by BertLindeman** [laurensvalk/segway#11] opened 2017-10-30 07:29 UTC
The [building instructions](http://robotsquare.com/2014/06/23/tutorial-building-balanc3r/) state you can use:

1x Gyroscopic Sensor. 
Use one of the following sensors:
- EV3 Gyro by LEGO (pictured below)
- NXT Gyroscope by HiTechnic

Running segway.py with the driver for the HiTechnic gyro sensor set like this:
```echo ht-nxt-gyro > /sys/class/lego-port/port1/set_device```

The program ends like this:
```
Traceback (most recent call last):
  File "./segway.py", line 52, in <module>
    gyroSensor.mode     = gyroSensor.MODE_GYRO_RATE
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1716, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: GyroSensor is not connected
```
Second attenpt with the HT gyro set as default analog device ends quite the same:
```
Traceback (most recent call last):
  File "./segway.py", line 52, in <module>
    gyroSensor.mode     = gyroSensor.MODE_GYRO_RATE
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1716, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: GyroSensor is not connected
```

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2017-10-24
Kernel version:     4.9.49-ev3dev-1.5.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016535166E2
BOARD_INFO_TYPE=main
```

The segway is so much fun! Thanks for that Laurens.

**Comment by laurensvalk** [comment] 2017-10-30 08:04
## Sensor config

You can leave the HT Sensor in nxt-analog mode. That will give you the full resolution. The code is already set up to do the appropriate conversions. We just need to change a scaling constant, as explained below.

Here is the part you'll want to change. Keep in mind that the sensor is automatically correctly set up, but the ev3dev Python library is used to easily find the location of the "value0" file that contains the sensor value.
```
# Gyro Sensor setup
gyroSensor          = ev3.GyroSensor()          # Replace by something like nxt-analog (not sure about its name)
gyroSensor.mode     = gyroSensor.MODE_GYRO_RATE # Remove this. The HT Gyro can only provide the rate anyway
gyroSensorValueRaw  = open(gyroSensor._path + "/value0", "rb")  # This opens the value0 file containing the sensor value we want. 
```
If there is nothing like "analog" in the Python library, keep only the last line, and provide the path yourself (/sys/class/lego-sensor/path/to/value/0/file)

## Converting the units

The code was designed with support for other sensors in mind. The angular rate is calculated like this:

```
gyroRate = (gyroRateRaw - gyroOffset)*radiansPerSecondPerRawGyroUnit # Don't change this formula, it's just here to explain it
```
The offset and the scaling vary between the sensors. The offset is automatically calculated by the program in the calibration step, so you won't have to change that.

The scaling is configured by this constant:

```
degPerSecondPerRawGyroUnit     = 1   # For the LEGO EV3 Gyro in Rate mode, 1 unit = 1 deg/s
```
For the HiTechnic sensor, use 0.2084 for this constant.

I think the positive rotation rate was the same for the HT Sensor as for the LEGO Gyro. But if it isn't, you can mount the sensor on the other side of the Brick (swap it with the Touch Sensor.)

**Comment by BertLindeman** [comment] 2017-10-30 08:11
Thank you for the to-the-point and as always well documented response. 
Will try and report back.

**Comment by laurensvalk** [comment] 2017-10-30 08:20
Thank you for bringing it up :)

Look forward to hear how it goes.

**Comment by BertLindeman** [comment] 2017-10-30 11:02
First short report: 
Did the software update you indicated and swapped the touch and HiTech gyro as the wheels were turning the wrong way.
A  bit jerky but stable with all debian services active and using wifi.
Stays up for a minute or so and then oscilates out of control and drops.
Will do a more detailed report later today.

**Comment by BertLindeman** [comment] 2017-10-30 14:04
# Status
Running EV3-brick on Image: ev3dev-stretch-ev3-generic-2017-10-24
Updated and added several packages I like; e.g. figlet bc joe bash-completion logwatch and more
So it's NOT a clean image anymore.

* Connect via ssh over wifi as user robot
```
cd ~
mkdir test_segway
cd test_segway/ 
wget https://github.com/laurensvalk/segway/raw/master/ev3/ev3dev/python/segway.py
wget https://github.com/laurensvalk/segway/raw/master/ev3/ev3dev/python/parameters.py
chmod +x segway.py
```
* Status of segway.py and parameter.py according to github:
Latest commit 5d6dcf6 20 days ago @laurensvalk laurensvalk Tuning

* HiTechnic Gyro sensor at default ANALOG-0 mode.
To be sure: Test unadapted segway.py - fails as expected; Oke.

# Modifications
## Software change: 
Adapt segway.py:
Changed this:
```
# Gyro Sensor setup   /BL 20171030
# gyroSensor          = ev3.GyroSensor()
# gyroSensor.mode     = gyroSensor.MODE_GYRO_RATE
# gyroSensorValueRaw  = open(gyroSensor._path + "/value0", "rb")
```
Into this:
```
gyroSensor          = ev3.Sensor(address="ev3-ports:in2")
gyroSensorValueRaw  = open(gyroSensor._path + "/value0", "rb")
```

## Hardware change:
Added touch sensor as building instructions I used did not yet have it :-) .
Swap the touch sensor and the gyro sensor as the wheels turn "the wrong way":
Touch sensor on the "speaker-side"
Gyro sensor on the "sd and USB" side


# Seen results:
- FUN 
- Still all debian services active and using wifi: A bit jerky but stable.
- Stays up for a minute or a bit less sometimes and then oscillates out of control and drops.
- A very slight turn to the left while balancing
- Sometimes a rush forward or backward occurs 20~40cm and *is* recovered
- start balancing is a bit picky with how correct I keep the robot up-right, sometimes almost direct dropdown


# Question (I am not a python expert - far off even )
The "Platform specific constants and conversions" are within the main loop.
Assume they do not change while running.
Might it help a tiny bit for speed to move them to the part where the sensors/motors are setup?
I ask because this may improve simple usability:
The type of giro could be determined in the program without modification and
at the same location set the constatns accordingly. 

Suggested part of the gyro setup:
```
# Gyro Sensor setup   /BL 20171030 START Gyro determination
gyroSensor          = ev3.GyroSensor()
if gyroSensor._path == None:
    eprint("No EV3.GyroSensor connected; try an analog sensor")
    gyroSensor          = ev3.Sensor(address="ev3-ports:in2")
    if gyroSensor._path == None:
        eprint("No sensor connected to input port-2; Quitting")
        exit()
    else:
        # check that this *is* a default analog sensor:
        eprint("Path to Gyro=" + str(gyroSensor._path))
        eprint("        Mode=" + str(gyroSensor.mode))
        if gyroSensor.mode != "ANALOG-0":
            eprint("No ANALOG sensor with mode: ANALOG-0 is connected to input port-2; Quitting")
            exit()
        else:
            eprint("Using sensor at '" + gyroSensor.address + "' with mode " + gyroSensor.mode)
            degPerSecondPerRawGyroUnit     = 0.2084                                # For the HiTechnic Gyro in ANALOG-0 mode, 1 unit = 0.2084 deg/s
else:
    gyroSensor.mode     = gyroSensor.MODE_GYRO_RATE
    gyroSensorValueRaw  = open(gyroSensor._path + "/value0", "rb")
    degPerSecondPerRawGyroUnit     = 1                                             # For the LEGO EV3 Gyro in Rate mode, 1 unit = 1 deg/s
    eprint("Using EV3.GyroSensor at '" + gyroSensor.address + "' with mode " + gyroSensor.mode)

#                     /BL 20171030 END Gyro determination
```
And the variable setting degPerSecondPerRawGyroUnit removed from further down

I can only test the HT-gyro as I do not have any other...

**Comment by laurensvalk** [comment] 2017-10-30 14:33
Thanks for the detailed response!

> gyroSensor          = ev3.Sensor(address="ev3-ports:in2")

Thanks for working this out, that is useful to know. I'll look at adding something like this to the code. 

> FUN

:thumbsup:

> A very slight turn to the left while balancing

Since you've tried the EV3-G version you probably noticed that it compensates for this. Maybe I should add this feature here too. The steering is caused by a slight difference in friction of the motors, which is especially apparent at low speeds.

> Swap the touch sensor and the gyro sensor as the wheels turn "the wrong way"

I'll look at implementing the orientation in software. Changing minus signs quickly gets very confusing, so I am not going to suggest you try that.**

> The "Platform specific constants and conversions" are within the main loop.

I don't think that's currently the case. Note that there are two loops. The outermost loop defines the constants and resets sensors, prior to starting the balancing loop with the Touch Sensor.

-----

** Just too tempting. Try changing 0.2084 to -0.2084 instead of mounting the sensor on the other side.

**Comment by BertLindeman** [comment] 2017-10-30 15:39
Thanks Laurens. 

> ** Just too tempting. Try changing 0.2084 to -0.2084 instead of mounting the sensor on the other side.

Maybe just to make it a bit clearer to the reader: set it as 
```
# Negative value for the HiTechnic sensor to prevent turning the wrong way: 
degPerSecondPerRawGyroUnit     = 0 - 0.2084 
#
```
Tried this and that works, so there is no hardware mod needed.

> I don't think that's currently the case. Note that there are two loops. The outermost loop defines the constants and resets sensors, prior to starting the balancing loop with the Touch Sensor.

Correct of course. I just want to keep the setting of the constants together as best as possible.
And the degPerSecondPerRawGyroUnit needs to be set near the gyro setup.

There is not much spare time for me the next days, but if I can test, just ping me.

**Comment by laurensvalk** [comment] 2017-11-05 15:35
> Tried this and that works, so there is no hardware mod needed.

This was my mistake --- for some reason I mounted the [HiTechnic sensor on the other side of the brick in the building instructions](http://robotsquare.com/2014/06/23/tutorial-building-balanc3r/), which is rather confusing.

If it is mounted like the EV3 Gyro, no minus sign is needed, as you correctly found out. Both sensor have the same "positive rotation rate" direction.

**Comment by laurensvalk** [comment] 2017-11-05 15:36
I updated the code to add support for the HiTechnic sensor. Right now without the minus sign: so the sensor is mounted just like the EV3 Gyro.

**Comment by BertLindeman** [comment] 2017-11-05 17:05
Ehrm, @laurensvalk Just downloaded the current segway.py and parameters.py and tested on my EV3 brick with my HiTechnic Gyro. (Latest commit 6c278d4 )
Had to add the negative sign to get the robot balancing. 
The gyro is mounted on the "speaker" side of the brick. 
After negating the robot *does* balance, not perfect but sometime anyway.
Maybe add a print about the time "standing"?

**Comment by laurensvalk** [comment] 2017-11-05 17:07
Yes, see my note above :smile:

**Comment by BertLindeman** [comment] 2017-11-05 17:15
Aaaahhh, right, so my Gyro is on the wrong side :-( 
"grumble" I did not have the correct "picture" of the build in my mind.
Sorry for the noise ;-)
Anyway the gyro detection also works for me, thank you.

**Comment by laurensvalk** [comment] 2017-11-05 20:03
Thanks for your help and providing the piece of code to enable the HiTechnic Sensor! I'll close this issue then.

> After negating the robot does balance, not perfect but sometime anyway.

Feel free to open a new issue for this. It seems to work allright for me. I wonder what might be causing the difference between our robots.

**Closed as completed by laurensvalk** 2017-11-05 20:03 UTC

**Comment by laurensvalk** [comment] 2017-11-06 08:28
I actually meant a new issue about the "imperfect balancing and only for some time" part, but you're right, I'll have to fix the HT Gyro placement too.
